Bluetooth: Mesh: add tf-m support for ble mesh
alxelax/zephyr pull request #10
Opened 2023-06-06 14:24 UTC by alxelax

This PR adds ability to build mesh with tf-m psa
for platforms those support tf-m.

2023-06-08 07:05 UTC, Andrewpini requested changes
Couple of clarifications and nitpics

2023-06-08 07:05 UTC, Andrewpini commented on samples/bluetooth/hci_rpmsg/bt_mesh_overlay.conf
> +# configuration if it has been changed. 1 adv is by default.
```suggestion
# The number of advertisement instances should be taken from ble mesh
# configuration if it has been changed. 1 adv is by default.
```
Is the intended meaning here that the number of adv sets is the default config setting, and that it should stick to that whenever the default configuration is changed? And is it neccesary to write the default value is 1? If it changes some day, will we remember to change this comment?

2023-06-08 07:05 UTC, Andrewpini commented on samples/bluetooth/mesh/nrf53_cpuapp_ns_overlay.conf
> +# Known issue: non secure platforms do not work with settings subsystem.
I like comments like this 👍

2023-06-08 07:05 UTC, Andrewpini commented on subsys/bluetooth/mesh/Kconfig
> +	  For more platforms details see TF-M documentation.
```suggestion
	  For more platform details see TF-M documentation.
```

2023-06-08 10:22 UTC, alxelax commented on samples/bluetooth/hci_rpmsg/bt_mesh_overlay.conf
> +# configuration if it has been changed. 1 adv is by default.
The comment has been removed since it creates more questions than answers.

2023-06-08 10:27 UTC, PavelVPV requested changes

2023-06-08 10:27 UTC, PavelVPV commented on samples/bluetooth/mesh_provisioner/nrf53_cpuapp_ns_overlay.conf
> +CONFIG_BT_MESH_USES_TFM_PSA=y
Aren't they mutually exclusive since they are under `choice`?

2023-06-08 10:27 UTC, PavelVPV commented on subsys/bluetooth/mesh/Kconfig
> +	select EXPERIMENTAL
This should not be possible to select without TFM, `depends on BUILD_WITH_TFM`?

2023-06-08 10:27 UTC, PavelVPV commented on samples/bluetooth/mesh_provisioner/CMakeLists.txt
> +endif()
Do we really need to define this in every sample? Isn't this a problem of build system? Can this be done in `modules/trusted-firmware-m/CMakeLists.txt` somewhere after this line (worked at my desk): https://github.com/zephyrproject-rtos/zephyr/blob/22b889e3b49def0a6423203581596076d2ef9c38/modules/trusted-firmware-m/CMakeLists.txt#L154?

2023-06-08 10:27 UTC, PavelVPV commented on samples/bluetooth/mesh_demo/sample.yaml
> +  sample.bluetooth.mesh.tfm:
```suggestion
  sample.bluetooth.mesh_demo.tfm:
```

2023-06-08 10:27 UTC, PavelVPV commented on samples/bluetooth/mesh/prj.conf
> -CONFIG_BT_TINYCRYPT_ECC=y
Should it be removed for microbit_gatt.conf? Then microbit will also access controller function directly.

2023-06-08 10:27 UTC, PavelVPV commented on samples/bluetooth/hci_rpmsg/bt_mesh_overlay.conf
If we want this configuration to be used by mesh samples, then we need to write this in sample's README files like, for example, it is done here:
https://github.com/zephyrproject-rtos/zephyr/blob/242c8f1c7727b74af758ecbe235aecf161594f48/samples/bluetooth/direction_finding_central/README.rst?plain=1#L39-L54

Though it would probably be better to do the same as done in, for example, direction finding sample readme where it suggests to copy the prj.conf to the hci_rpmsg sample and then the network core compiles with that configuration. This way can avoid having misconfiguration of network core and application core for a definite sample. On the other hand, if controller configuration is the same, single file is better.

If you chose to keep single file, then I'd suggest to rename it to `nrf5340_cpunet_bt_mesh-bt_ll_sw_split.conf` to align with other names. I think `bt_ll_sw_split` suffix would make sense because in nRF Connect SDK we have a dedicated file for network core configuration.

2023-06-08 10:27 UTC, PavelVPV commented on samples/bluetooth/hci_rpmsg/bt_mesh_overlay.conf
> +CONFIG_BT_CTLR_DUP_FILTER_LEN=0
This configuration is missing in `mesh_provisioner` sample. I guess it should be added there to have the same configuration on nRF52 and nRF53 platforms.

2023-06-08 10:27 UTC, PavelVPV commented on samples/bluetooth/mesh_provisioner/sample.yaml
> +  sample.bluetooth.mesh.tfm:
```suggestion
  sample.bluetooth.mesh_provisioner.tfm:
```

2023-06-08 10:27 UTC, PavelVPV commented on samples/bluetooth/mesh_demo/nrf53_cpuapp_ns_overlay.conf
Board specific files can be moved under `boards` folder and keep board name in the file name without `_overlay` suffix: `nrf5340dk_nrf5340_cpuapp_ns.conf`. Then the sample can be build with just specifying board name. The file will be picked up by build system and merged with `prf.conf` of the sample. Same works for the network core I think. This will also not require special configuration (`extra_args`) for twister.

2023-06-08 11:16 UTC, alxelax commented on samples/bluetooth/mesh_provisioner/CMakeLists.txt
> +endif()
I picked up this template from tf-m samples. I'm not sure that this is good idea to add in `modules/trusted-firmware-m/CMakeLists.txt` file the dependency on path to not existing folders\files. That path to files and files themselves are created dynamically during application compilation.

2023-06-08 11:58 UTC, PavelVPV commented on samples/bluetooth/mesh_provisioner/CMakeLists.txt
> +endif()
We seems really strange and should be discussed with code owners of `modules/trusted-firmware-m/CMakeLists.txt` I guess.

2023-06-08 12:34 UTC, alxelax commented on samples/bluetooth/mesh_provisioner/CMakeLists.txt
> +endif()
Any case it should be fixed on general manner for all samples and not in mesh related PR

2023-06-08 12:44 UTC, PavelVPV commented on samples/bluetooth/mesh_provisioner/CMakeLists.txt
> +endif()
I'd prefer if we ask this and don't change the our samples CMakeLists.txt. It won't brake other samples if we do the change.

2023-06-08 12:51 UTC, alxelax commented on samples/bluetooth/mesh_provisioner/CMakeLists.txt
> +endif()
Where do you want me to ask them?

2023-06-08 13:15 UTC, alxelax commented on samples/bluetooth/hci_rpmsg/bt_mesh_overlay.conf
I do not like `direction finding` approach since they do not have their configuration in CI. The only way to build it is manual.

2023-06-08 13:16 UTC, PavelVPV commented on samples/bluetooth/mesh_provisioner/CMakeLists.txt
> +endif()
In TF-M support channel? Or simply change it here and create PR. If the change is rejected, then will do this change in every sample.

2023-06-08 13:44 UTC, PavelVPV commented on samples/bluetooth/mesh_provisioner/CMakeLists.txt
> +endif()
Asked Joakim leave this as is as there are some issues with this still :(
https://github.com/zephyrproject-rtos/zephyr/pull/53097#issuecomment-1353157554

2023-06-08 13:54 UTC, alxelax commented on samples/bluetooth/mesh_demo/nrf53_cpuapp_ns_overlay.conf
I really want this option for any platform (including potential new Nordic's platforms), not only for nrf53 to avoid creation files for every new one. Probably it's worth to remove platform from file name and add `tfm` instead.

2023-06-08 14:08 UTC, PavelVPV commented on samples/bluetooth/mesh_demo/nrf53_cpuapp_ns_overlay.conf
But this is what we do even between thingy53 and nrf5340dk: https://github.com/nrfconnect/sdk-nrf/tree/main/samples/bluetooth/mesh/light_ctrl/boards

2023-06-08 14:10 UTC, PavelVPV commented on samples/bluetooth/mesh_demo/nrf53_cpuapp_ns_overlay.conf
If we want mesh always compile with `CONFIG_BT_MESH_USES_TFM_PSA` when TFM is supported, then default value for `BT_MESH_CRYPTO_LIB` choice should be updated, e.g.:
```
choice BT_MESH_CRYPTO_LIB
	prompt "Crypto library selection for mesh security"
	default BT_MESH_USES_TFM_PSA if BUILD_WITH_TFM
	default BT_MESH_USES_TINYCRYPT
```
Not sure though if it is correct to use `BUILD_WITH_TFM` but not some other option.

2023-06-08 14:15 UTC, PavelVPV commented on samples/bluetooth/mesh_demo/nrf53_cpuapp_ns_overlay.conf
The overlay config will still be needed to disable settings and this should be fine.

2023-06-08 14:17 UTC, PavelVPV commented on samples/bluetooth/hci_rpmsg/bt_mesh_overlay.conf
But do we really need to add support for nRF53 in samples? What if we use https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/bluetooth/mesh/basic for checking that mesh builds with tfm by adding one more overlay there?

2023-06-09 06:53 UTC, alxelax commented on samples/bluetooth/hci_rpmsg/bt_mesh_overlay.conf
tfm is not mesh feature. Why should it be added to test that checks mesh features? How about combinations friend and tfm, friend without tfm etc etc? 
I do not see any reason to not provide people tfm based mesh in samples especially when tinycrypt has deprecated status.

2023-06-09 06:56 UTC, alxelax commented on samples/bluetooth/hci_rpmsg/bt_mesh_overlay.conf
> But do we really need to add support for nRF53 in samples? What if we use https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/bluetooth/mesh/basic for checking that mesh builds with tfm by adding one more overlay there?

Exact this sample is for network core.

2023-06-12 08:13 UTC, Andrewpini approved these changes

2023-06-13 07:33 UTC, PavelVPV commented on samples/bluetooth/hci_rpmsg/bt_mesh_overlay.conf
I understand this. The point is that the current support has not sense without settings. So if the goal is to ensure that mesh compiles with TFM, then adding another target to `basic` test should be enough. Samples without settings has not sense and they (as you may see) don't have combinations of all features so the point about with and without friend doesn't work here.

2023-06-13 07:36 UTC, alxelax commented on samples/bluetooth/hci_rpmsg/bt_mesh_overlay.conf
Kind of disagree. These samples are just for feature demonstration and cannot be used for anything else. Btw. this is mentioned in sample documentation. For demonstration purposes, mesh without settings is good enough.

2023-06-13 14:06 UTC, PavelVPV commented on samples/bluetooth/hci_rpmsg/nrf5340_cpunet_bt_mesh-bt_ll_sw_split.conf
> +CONFIG_BT_EXT_ADV=y
Missing CONFIG_BT_LL_SW_SPLIT?

2023-06-13 14:06 UTC, PavelVPV commented on samples/bluetooth/mesh_demo/nrf53_cpuapp_ns_overlay.conf
I still disagree with using any names other than the board name because this is how it is designed in Zephyr currently. You also won't need another target for twister and can just add `nrf5340dk_nrf5340_cpuapp_ns` to `platform_allow`.

2023-06-14 14:37 UTC, PavelVPV approved these changes

2023-06-16 11:43 UTC, mia-ko requested changes

2023-06-16 11:43 UTC, mia-ko commented on samples/bluetooth/mesh/README.rst
> +also run on the network core. The :ref:`bluetooth-hci-rpmsg-sample` sample
```suggestion
To run the application on an :ref:`nrf5340dk_nrf5340`, a Bluetooth controller application must
also run on the network core. The :ref:`bluetooth-hci-rpmsg-sample` sample
```

2023-06-16 11:43 UTC, mia-ko commented on samples/bluetooth/mesh_demo/README.rst
> +also run on the network core. The :ref:`bluetooth-hci-rpmsg-sample` sample
```suggestion
To run the application on an :ref:`nrf5340dk_nrf5340`, a Bluetooth controller application must
also run on the network core. The :ref:`bluetooth-hci-rpmsg-sample` sample
```

2023-06-16 11:43 UTC, mia-ko commented on samples/bluetooth/mesh_provisioner/README.rst
> +also run on the network core. The :ref:`bluetooth-hci-rpmsg-sample` sample
```suggestion
To run the application on an :ref:`nrf5340dk_nrf5340`, a Bluetooth controller application must
also run on the network core. The :ref:`bluetooth-hci-rpmsg-sample` sample
```

2023-06-19 08:16 UTC, alxelax commented
I close this PR.
Since the parent PR has been merged and upstream is unfrozen, I created PR to upstream with all fixes from this PR. Please take a look it there: https://github.com/zephyrproject-rtos/zephyr/pull/59347
@mia-ko, I cannot find you in the reviewer list in upstream. Please join to PR and check my changes to your comments.

2023-06-19 08:16 UTC, closed without merging