Mesh babblesim on mbedtls psa
alxelax/zephyr pull request #4
Opened 2022-07-12 12:21 UTC by alxelax

PR adds support mbedtls PSA for public\private pair generating.
It adds also compile time choice between tinycrypt and mbedtls.

2022-07-13 07:11 UTC, PavelVPV requested changes

2022-07-13 07:11 UTC, PavelVPV commented on tests/bluetooth/bsim_bt/bsim_test_mesh/src/test_provision.c
> +#if defined CONFIG_BT_MESH_USES_TINYCRYPT
I don't think we need to support tests for both. Otherwise we need to compile 2 binaries for each crypto library.

2022-07-13 07:13 UTC, PavelVPV commented
FYI: If create a PR to `dh_psa` branch, only the changes in this branch will be shown. Once `dh_psa` is merged, it is possible to change target branch to `main`. Changing target branch is possible within the same repository.

2022-07-14 09:31 UTC, PavelVPV approved these changes

2022-07-14 12:57 UTC, omkar3141 approved these changes
Note, with this, we will permanently remove tinycrypt dependencies and checks from the testing.

2022-07-14 13:27 UTC, merged